// Code generated by "stringer -type=TaskState"; DO NOT EDIT.

package jobrunner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-1]
	_ = x[Running-2]
	_ = x[Finished-3]
}

const _TaskState_name = "IdleRunningFinished"

var _TaskState_index = [...]uint8{0, 4, 11, 19}

func (i TaskState) String() string {
	i -= 1
	if i < 0 || i >= TaskState(len(_TaskState_index)-1) {
		return "TaskState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TaskState_name[_TaskState_index[i]:_TaskState_index[i+1]]
}
